### ISSUE TITLE
FATAL Cannot find module

### ISSUE THREAD

**Issue by CNiceToUpp** [grzhan/hexo-tag-aplayer#11]
@grzhan @yrocq @Myer921 
### the detail error info:

```
$ hexo
FATAL Cannot find module '/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/hexo-tag-aplayer'
Error: Cannot find module '/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/hexo-tag-aplayer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/hexo/lib/hexo/load_plugins.js:52:24
    at tryCatcher (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:636:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._filter (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/bluebird/js/release/promise.js:612:10)
```

**Comment by grzhan** [comment]
It looks like you don't have `hexo-tag-plugin` installed.

Try reinstall this plugin under your site directory: `npm install --save  --no-optional hexo-tag-aplayer`.  

Then check if this plugin is installed (`/Users/hechao/Documents/TechBlog/CniceToUpp/node_modules/hexo-tag-aplayer`)

I apologize for the delay in getting back to you.

**Comment by tc9011** [comment]
I occur this error too，and hexo-tag-aplayer is already exists.

**Comment by grzhan** [comment]
@tc9011 Could you please provide more details about environment (your system, version of node.js, version of hexo and version of this plugin)

**Comment by tc9011** [comment]
@grzhan  system:macos sierra10.12.2 ; hexo: "3.2.2";nodejs:5.9.1;hexo-tag-aplayer: "^2.0.0".
I operate any hexo command, occur this error FATAL Cannot find module,but hexo-tag-dplayer doesn't have this problem.
thank you for your reply:)

**Comment by grzhan** [comment]
@tc9011 It's my fault.

Now, this problem can be solved by updating `hexo-tag-apalyer` to the new version (`2.0.1`)

**Comment by tc9011** [comment]
@grzhan  thank you,I'll try again  : )
